controllers/empleado_controller.py
from flask import Blueprint, request, render_template, redirect, url_for, flash, session
from models.empleado import Empleado
from utils.utils import login_required
from views import empleado_view

empleado_bp = Blueprint('empleado', __name__, url_prefix='/empleados')

@empleado_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        # Lógica de autenticación
        nombre = request.form['nombre']
        contrasena = request.form['contrasena']
        empleado = Empleado.query.filter_by(nombre=nombre).first()

        if empleado and empleado.verify_password(contrasena):  # Comparación de contraseña
            # Verificación del estado del empleado
            if empleado.estado == 'Activo':
                session['empleado_id'] = empleado.id_emp
                session['empleado_nombre'] = empleado.nombre
                session['empleado_cargo'] = empleado.cargo  # Guardar el cargo en la sesión
                flash('Inicio de sesión exitoso', 'success')
                return redirect(url_for('main.index'))
            else:
                flash('Tu cuenta está inactiva. Por favor, contacta con el administrador.', 'danger')
        else:
            flash('Credenciales incorrectas, intenta de nuevo', 'danger')

    return render_template('login.html')


@empleado_bp.route('/logout')
def logout():
    session.pop('empleado_id', None)
    session.pop('empleado_nombre', None)
    flash('Sesión cerrada correctamente', 'info')
    return redirect(url_for('main.index'))





# Ruta para registrar un empleado
@empleado_bp.route("/registrar", methods=['GET', 'POST'])
@login_required
def registrar():
    if request.method == 'POST':
        nombre = request.form['nombre']
        apellidos = request.form['apellidos']
        cargo = request.form['cargo']
        contrasena = request.form['contrasena']
        estado = request.form.get('estado', 'Activo')

        # Validaciones básicas antes de guardar
        if not nombre or not apellidos or not cargo or not contrasena:
            flash("Todos los campos son requeridos", "error")
            return redirect(url_for('empleado.registrar'))

        empleado = Empleado(nombre, apellidos, cargo, contrasena, estado)
        empleado.save()  # Guardar el nuevo empleado en la base de datos
        flash("Empleado registrado exitosamente", "success")
        return redirect(url_for('empleado.index'))

    return empleado_view.registrar()


# Ruta para editar un empleado
@empleado_bp.route("/editar/<int:id_emp>", methods=['GET', 'POST'])
@login_required
def editar(id_emp):
    empleado = Empleado.get_by_id(id_emp)
    if not empleado:
        flash("empleado no encontrado", "error")
        return redirect(url_for('empleado.index'))

    if request.method == 'POST':
        nombre = request.form['nombre']
        apellidos = request.form['apellidos']
        cargo = request.form['cargo']
        contrasena = request.form['contrasena']
        estado = request.form['estado']

        # Validaciones básicas antes de actualizar
        if not nombre or not apellidos or not cargo or not contrasena or not estado:
            flash("Todos los campos son requeridos", "error")
            return redirect(url_for('empleado.editar', id_emp=id_emp))

        empleado.update(nombre=nombre, apellidos=apellidos, cargo=cargo, contrasena=contrasena,estado=estado)
        flash("empleado actualizado exitosamente", "success")
        return redirect(url_for('empleado.index'))

    return empleado_view.editar(empleado)


# Ruta para eliminar un empleado
@empleado_bp.route("/delete/<int:id_emp>")
@login_required
def delete(id_emp):
    empleado = Empleado.get_by_id(id_emp)
    if not empleado:
        flash("empleado no encontrado", "error")
        return redirect(url_for('empleado.index'))

    empleado.delete()  # Eliminar el empleado de la base de datos
    flash("empleado eliminado exitosamente", "success")
    return redirect(url_for('empleado.index'))


@empleado_bp.route('/')
@login_required
def index():
    empleados = Empleado.get_all()  # Obtiene la lista de empleados desde el modelo
    return empleado_view.list(empleados)  # Renderiza la vista con los empleados

templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} - Joyería Luxor</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/style.css">
    <link rel="stylesheet" href="../../static/style.css">
</head>
<body>
    <nav class="navbar">
        <div class="nav-links">
            <a href="/" class="nav-item">INICIO</a>

            {% if session.get('empleado_id') %}
                <a href="/clientes/" class="nav-item">CLIENTES</a>
                <a href="/productos/" class="nav-item">PRODUCTOS</a>
                <a href="/ventas/" class="nav-item">VENTAS</a>
                <a href="/compras/" class="nav-item">COMPRAS</a>
                
                {% if session.get('empleado_cargo') == 'Administrador' %}
                <a href="{{ url_for('empleado.index') }}" class="nav-item">EMPLEADOS</a>
                {% endif %}
            {% endif %}
        </div>
        <div class="nav-auth">
            {% if session.get('empleado_id') %}
                <span class="admin-button">{{ session.get('empleado_nombre', 'Usuario') }}</span>
                <a href="{{ url_for('empleado.logout') }}" class="nav-item">Cerrar Sesión</a>
            {% else %}
            <a href="{{ url_for('empleado.login') }}" class="nav-item">Iniciar Sesión</a>

            {% endif %}
        </div>
    </nav>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer class="footer">
        <div class="footer-brand">JOYERÍA LUXOR</div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block title %}Inicio{% endblock %}

{% block content %}
<div class="hero-section">
    <div class="hero-content text-center py-5">
        <h1 class="display-4">Joyería Luxor</h1>
        <p class="lead welcome-text">
            Bienvenido a Joyería Luxor, donde la elegancia armoniza y los diseños de vanguardia se unen para crear joyas que perduran en el tiempo.
        </p>
        <div class="hero-buttons mt-4">
            <button class="btn btn-primary btn-lg" onclick="scrollToCatalog()">Ver Catálogo</button>
            <button class="btn btn-success btn-lg" onclick="scrollToInfo()">Comprar Ahora</button>
        </div>
    </div>
    <div class="hero-image text-center">
        <img src="{{ url_for('static', filename='img/jewelry-store.png') }}" alt="Interior de la joyería" class="img-fluid mt-4">
    </div>
</div>
<div class="luxury-section">
    <h2 class="text-center mb-4">Artesanía y Diseño de Lujo</h2>
    <div class="luxury-content">
        <div class="luxury-column">
            <h3>Nuestra Historia</h3>
            <p>Joyería Luxor es una empresa familiar con más de 30 años de tradición. Nos enorgullecemos de nuestro legado de excelencia y llevar las más altas normas de calidad a cada una de nuestras creaciones.</p>
        </div>
        <div class="luxury-column">
            <h3>Diseño Exclusivo</h3>
            <p>Nuestros diseñadores trabajan arduamente para crear piezas únicas que reflejen la elegancia y el estilo de nuestros clientes. Cada joya es una obra de arte diseñada con pasión y atención al detalle.</p>
        </div>
    </div>
</div>
<div id="catalog-section" class="luxury-section py-5">
    <h2 class="text-center mb-4">Nuestro Catálogo</h2>
    <div class="table-responsive">
        <table class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>Nombre</th>
                    <th>Precio</th>
                    <th>Disponibilidad</th>
                </tr>
            </thead>
            <tbody>
                {% for item in productos %}
                <tr>
                    <td>{{ item.nombre }}</td>
                    <td>{{ item.precio }} Bs.</td>
                    <td>{{ item.disponibilidad }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<div id="services-section" class="services-section py-5">
    <div class="container">
        <h2 class="text-center mb-4">Nuestros Servicios</h2>
        <div class="row">
            <div class="col-md-6">
                <h5>Personalización de Joyas</h5>
                <p>Diseñamos joyas exclusivas según tus necesidades y preferencias. Trabajamos contigo para crear la pieza perfecta.</p>
            </div>
            <div class="col-md-6">
                <h5>Reparación y Mantenimiento</h5>
                <p>Ofrecemos servicios de reparación, limpieza y mantenimiento para que tus joyas luzcan siempre como nuevas.</p>
            </div>
        </div>
    </div>
</div>

<!-- New Testimonial Section -->
<div id="testimonials-section" class="testimonials-section py-5 bg-white text-dark">
    <div class="container">
        <h2 class="text-center mb-4">Testimonios de Nuestros Clientes</h2>
        <div class="row">
            <div class="col-md-4">
                <blockquote class="blockquote text-center">
                    <p>"El mejor servicio que he recibido. Las joyas son impresionantes y de calidad inigualable."</p>
                </blockquote>
            </div>
            <div class="col-md-4">
                <blockquote class="blockquote text-center">
                    <p>"Recomiendo Joyería Luxor a todos mis amigos. ¡No podrían estar más felices!"</p>
                   
                </blockquote>
            </div>
            <div class="col-md-4">
                <blockquote class="blockquote text-center">
                    <p>"Encontré el regalo perfecto aquí. Su atención al detalle es impresionante."</p>
                   
                </blockquote>
            </div>
        </div>
    </div>
</div>

<div id="info-section" class="store-info-section py-5 bg-light">
    <div class="container">
        <h2 class="text-center mb-4">Información de Nuestra Tienda</h2>
        <div class="row">
            <div class="col-md-4">
                <strong>
                <h5>Ubicación</h5>
                    <p>Avenida Principal #123, La Paz, Bolivia</p>
                    <p>Horario de Atención: Lunes a Sábado, 9:00 AM - 7:00 PM</p>
                </strong>
            </div>
            <div class="col-md-4">
                <strong>
                    <h5>Contacto</h5>
                    <p>Teléfono: 222 4512324</p>
                    <p>Email: contacto@joyerialuxor.com</p>
                    <p>WhatsApp: +591 65432189</p>
                </strong>
            </div>
            <div class="col-md-4">
                <h5>Redes Sociales</h5>
                <p>
                    <img src="../static/img/facebook_4494464.png" alt="Facebook" width="30" height="30"> <strong>JoyeriaLuxor</strong>
                    <br>
                    <br>
                    <img src="../static/img/instagram_4494468.png" alt="Instagram" width="30" height="30"> <strong>JoyeriaLuxor</strong>
                    <br>
                    <br>
                    <img src="../static/img/twitter_4494465.png" alt="Twitter" width="30" height="30"> <strong>JoyeriaLuxor</strong>

                </p>
            </div>
        </div>
    </div>
</div>



<script>
    function scrollToCatalog() {
        document.getElementById("catalog-section").scrollIntoView({ behavior: "smooth" });
    }

    function scrollToInfo() {
        document.getElementById("info-section").scrollIntoView({ behavior: "smooth" });
    }
</script>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block title %}Iniciar Sesión{% endblock %}

{% block content %}
<div class="login-container">
    <div class="login-box">
        <h2>Iniciar sesión</h2>

        <!-- Mensajes de flash -->
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <ul class="alert">
                    {% for category, message in messages %}
                        <li class="alert alert-{{ category }}" id="flash-message">{{ message }}</li>
                    {% endfor %}
                </ul>

                <script>
                    setTimeout(function() {
                        var flashMessage = document.getElementById('flash-message');
                        if (flashMessage) {
                            flashMessage.style.display = 'none';
                        }
                    }, 2000);  // 2000 milisegundos = 2 segundos
                </script>
            {% endif %}
        {% endwith %}

        <!-- Formulario de inicio de sesión -->
        <form method="POST">
            <div class="mb-3">
                <label for="" class="form-label">Nombre de usuario</label>
                <input type="text" class="form-control" id="" name="nombre" required>
            </div>
            <div class="mb-3">
                <label for="" class="form-label">Contraseña</label>
                <input type="password" class="form-control" id="" name="contrasena" required>
            </div>
            <button type="submit" class="btn btn-primary">Iniciar sesión</button>
        </form>
    </div>

</div>
{% endblock %}